version: "2"
linters:
  enable:
    - bodyclose
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - interfacebloat
    - revive
    - staticcheck
    - testifylint
  settings:
    revive:
      enable-default-rules: true
      rules:
        - name: var-naming
          disabled: false
          arguments:
            - []
            - []
            - - skip-package-name-checks: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
