linters:
  enable:
    - bodyclose
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - gci
    - gofmt
    - gosimple
    - govet
    - ineffassign
    - interfacebloat
    - revive
    - staticcheck
    - stylecheck
    - testifylint
    - unused
